const originalObj = {
    name: "John",
    age: 30,
    address: {
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345"
    }
  };
  let obj={
    "responseObject":{
        "actualValue":184486.4,
        "orderNo":"20508F9BB4F5E8F78AEE55F3805E1A4D8D46490A5DA18DA1",
        "customerId":"FBFB4116E0614149",
        "totalPremium":"2673.32",
        "orderVehicleDTO":{
            "id":52200,
            "actualValue":184486.4,
            "orderNo":"20508F9BB4F5E8F78AEE55F3805E1A4D8D46490A5DA18DA1",
            "isDelete":"0",
            "createdUser":"customerId:223854",
            "cityCode":"210200",
            "licenseNo":"辽B6Y666",
            "frameNo":"LUHKJHRKJGHKJERHG",
            "isRenewFlag":"0",
            "carOwner":"许利锋",
            "brandName":"雅阁HG7240轿车",
            "identifyExpiry":"",
            "identifyExpiryIsLong":"",
            "createdDate":1681800432000,
            "isCardbFlag":"0",
            "rbCode":"YGD1006GZB",
            "seatCount":5,
            "isNewEnergy":"N",
            "vehicleStyleDesc":"1",
            "engineNo":"876856435435156",
            "licenseType":"02",
            "useNatureCode":"02",
            "attachNature":"01",
            "carUseType":"01",
            "vehicleType":"100",
            "vehicleCategory":"K33",
            "enrollDate":1650211200000,
            "transferFlag":"0",
            "fuelType":"0",
            "carOwnerIdType":"01",
            "carOwnerIdNo":"110101199201010116",
            "carOwnerType":"1",
            "carOwnerProvinceCode":"",
            "carOwnerCityCode":"",
            "carOwnerDistrictCode":"",
            "carOwnerDamageAdress":"",
            "ecdemicFlag":"0",
            "isHaveGps":"1",
            "familyCarCount":1,
            "modifiedDate":1682044388000,
            "modifiedUser":"customerId:223854",
            "printBrandName":"雅阁HG7240轿车",
            "purchasePrice":198800,
            "travelAreaFlag":"3",
            "appointDriverFlag":"0",
            "carOwnerSex":"",
            "runMileRate":10000,
            "wholeWeight":1465,
            "isReinsFlag":"1",
            "userYear":1,
            "trafficClaimNum":0,
            "commercialClaimNum":0,
            "applicatFlag":""
        },
        "cityCode":"210200",
        "grantPoint":"0",
        "riskDataList":[
            {
                "amount":"184486.40",
                "premium":"1292.37",
                "coverageCode":"01",
                "coverageName":"机动车损失保险",
                "riskCode":"C731",
                "benchMarkPremium":"2584.73",
                "quantity":"0",
                "coverageType":"0",
                "unitAmount":"0",
                "deductableFlag":"0",
                "discount":"50.00",
                "mainCoverageCode":"",
                "riskRuleList":[
                    "184486.40"
                ],
                "calculateFlag":"1",
                "floatAmountFlag":"0"
            },
            {
                "amount":"0",
                "coverageCode":"02",
                "coverageName":"机动车第三者责任保险",
                "riskCode":"C731",
                "coverageType":"0",
                "deductableFlag":"0",
                "mainCoverageCode":"",
                "riskRuleList":[
                    "100000",
                    "150000",
                    "200000",
                    "300000",
                    "500000",
                    "1000000",
                    "1500000",
                    "2000000",
                    "3000000",
                    "5000000",
                    "8000000",
                    "6000000",
                    "4000000",
                    "10000000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"200000.00",
                "premium":"282.93",
                "coverageCode":"041",
                "coverageName":"机动车车上人员责任保险（司机）",
                "riskCode":"C731",
                "benchMarkPremium":"565.87",
                "quantity":"0",
                "coverageType":"0",
                "unitAmount":"200000",
                "deductableFlag":"0",
                "discount":"50.00",
                "mainCoverageCode":"",
                "riskRuleList":[
                    "5000",
                    "10000",
                    "20000",
                    "30000",
                    "50000",
                    "100000",
                    "200000"
                ],
                "calculateFlag":"1",
                "floatAmountFlag":"0"
            },
            {
                "amount":"300000.00",
                "premium":"1076.80",
                "coverageCode":"044",
                "coverageName":"机动车车上人员责任保险（乘客）",
                "riskCode":"C731",
                "benchMarkPremium":"2153.60",
                "quantity":"4",
                "coverageType":"0",
                "unitAmount":"300000",
                "deductableFlag":"0",
                "discount":"50.00",
                "mainCoverageCode":"",
                "riskRuleList":[
                    "5000",
                    "10000",
                    "20000",
                    "30000",
                    "50000",
                    "100000",
                    "200000"
                ],
                "calculateFlag":"1",
                "floatAmountFlag":"0"
            },
            {
                "amount":"0",
                "coverageCode":"83",
                "coverageName":"附加车轮单独损失险",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    "500",
                    "1000",
                    "2000",
                    "3000",
                    "4000",
                    "5000",
                    "8000",
                    "10000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"14",
                "coverageName":"附加新增加设备损失险",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"89",
                "coverageName":"附加医保外医疗费用责任险（机动车车上人员责任保险（乘客））",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"044",
                "riskRuleList":[
                    "10000",
                    "20000",
                    "50000",
                    "100000",
                    "30000",
                    "200000",
                    "30000",
                    "200000",
                    "-1"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"21",
                "coverageName":"附加车身划痕损失险",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    "2000",
                    "5000",
                    "10000",
                    "20000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"12",
                "coverageName":"附加修理期间费用补偿险",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"19",
                "coverageName":"附加法定节假日限额翻倍险",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"02",
                "riskRuleList":[
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"08",
                "coverageName":"附加车上货物责任险",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"25",
                "coverageName":"附加精神损害抚慰金责任险（机动车第三者责任保险）",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"02",
                "riskRuleList":[
                    "10000",
                    "20000",
                    "50000",
                    "100000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"78",
                "coverageName":"附加医保外医疗费用责任险（机动车第三者责任保险）",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"02",
                "riskRuleList":[
                    "10000",
                    "20000",
                    "50000",
                    "100000",
                    "200000",
                    "500000",
                    "1000000",
                    "2000000",
                    "3000000",
                    "4000000",
                    "5000000",
                    "6000000",
                    "8000000",
                    "10000000",
                    "-1"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"79",
                "coverageName":"道路救援服务特约条款",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    "2",
                    "7",
                    "12",
                    "17",
                    "22",
                    "",
                    "0"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"80",
                "coverageName":"车辆安全检测特约条款",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"85",
                "coverageName":"附加发动机进水损坏除外特约条款",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"81",
                "coverageName":"代为驾驶服务特约条款",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"82",
                "coverageName":"代为送检服务特约条款",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"601",
                "coverageName":"附加绝对免赔率特约险（机动车损失保险）",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    "0.05",
                    "0.1",
                    "0.15",
                    "0.2"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"602",
                "coverageName":"附加绝对免赔率特约险（机动车第三者责任保险）",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"02",
                "riskRuleList":[
                    "0.05",
                    "0.1",
                    "0.15",
                    "0.2"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"604",
                "coverageName":"附加绝对免赔率特约险（机动车车上人员责任保险（司机））",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"041",
                "riskRuleList":[
                    "0.05",
                    "0.1",
                    "0.15",
                    "0.2"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"86",
                "coverageName":"附加精神损害抚慰金责任险（机动车车上人员责任保险（司机））",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"041",
                "riskRuleList":[
                    "10000",
                    "20000",
                    "50000",
                    "100000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"87",
                "coverageName":"附加精神损害抚慰金责任险（机动车车上人员责任保险（乘客））",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"044",
                "riskRuleList":[
                    "10000",
                    "20000",
                    "50000",
                    "100000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"011",
                "coverageName":"车损险绝对免赔额",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"01",
                "riskRuleList":[
                    "300",
                    "500",
                    "1000",
                    "2000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"-1.00",
                "premium":"21.22",
                "coverageCode":"88",
                "coverageName":"附加医保外医疗费用责任险（机动车车上人员责任保险（司机））",
                "riskCode":"C731",
                "benchMarkPremium":"42.44",
                "quantity":"0",
                "coverageType":"1",
                "unitAmount":"0",
                "deductableFlag":"0",
                "discount":"50.00",
                "mainCoverageCode":"041",
                "riskRuleList":[
                    "10000",
                    "20000",
                    "50000",
                    "100000",
                    "30000",
                    "200000",
                    "-1"
                ],
                "calculateFlag":"1",
                "floatAmountFlag":"0"
            },
            {
                "amount":"0",
                "coverageCode":"605",
                "coverageName":"附加绝对免赔率特约险（机动车车上人员责任保险（乘客））",
                "riskCode":"C731",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"044",
                "riskRuleList":[
                    "0.05",
                    "0.1",
                    "0.15",
                    "0.2"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            }
        ],
        "isRenew":"0",
        "intermediaryCode":"018331A10119",
        "isNewEnergy":"N",
        "taxSwitch":"0",
        "biStartDate":"2023-04-22",
        "biEndDate":"2024-04-21",
        "minStartDate":"2023-04-22",
        "maxStartDate":"2023-07-20",
        "showPointFlag":"1",
        "showPointRateFlag":"1",
        "immedEffectFlag":"1",
        "scxlSaleFlag":"0",
        "immedEffectStart":"1",
        "immedEffectAdded":"1",
        "immedEffectEnd":"22",
        "biWholePrePayRateBasicPrice":0.5172,
        "biWholePrePayRateFloorPrice":1.0343,
        "biTianMaIndexFloorPrice":36.214,
        "biTianMaIndexBasicPrice":57.4234,
        "isCxwyOrder":"0",
        "premfactor1":"1.0",
        "lastEndDate":"",
        "lastStartDate":"",
        "biFjldSwitch":"0",
        "biFinalRates":0,
        "biDiscUpperLimit":1.5,
        "biDiscLowerLimit":0.5,
        "biSuggestDiscount":0,
        "elrLevelCOM":"d2",
        "hasBiFlag":"1",
        "hasCiFlag":"0",
        "hasTaxFlag":"0",
        "biPremium":"2673.32",
        "sumBjmpPremium":"0",
        "taxPayMode":"",
        "rcldPlanList":[
            {
                "isDefault":"0",
                "planCode":"1113",
                "propAccidentProductList":[
                    {
                        "model":"210,100",
                        "productCode":"313",
                        "productName":"驾平险B",
                        "policyType":"2",
                        "amount":1785000,
                        "premium":"100",
                        "isDefault":"0",
                        "carUseType":"01,05",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"99",
                        "riskAware":"按人投保，仅限驾驶非营运车，每人限购2份。",
                        "effectiveShare":"2",
                        "operatingAttribute":"02",
                        "maximumSeats":"5",
                        "propAccidentComboList":[
                            {
                                "comboName":"驾车人员意外伤害保险",
                                "coverage":"300000",
                                "comboDetail":"意外身故、残疾"
                            }
                        ]
                    }
                ],
                "planName":"驾车意外险"
            },
            {
                "isDefault":"0",
                "planCode":"1101",
                "propAccidentProductList":[
                    {
                        "productCode":"FA002149",
                        "productName":"驾乘无忧B（疫安心版）",
                        "policyType":"2",
                        "amount":595000,
                        "premium":"200",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"189",
                        "effectiveShare":"2",
                        "propAccidentComboList":[
                            {
                                "comboName":"锦程交通意外伤害保险",
                                "coverage":"50万",
                                "comboDetail":"交通意外身故残疾"
                            },
                            {
                                "comboName":"交通意外伤害医疗保险",
                                "coverage":"5万",
                                "comboDetail":"交通意外医疗"
                            },
                            {
                                "comboName":"意外伤害住院医疗补助条款",
                                "coverage":"250元/天",
                                "comboDetail":"意外伤害住院补助（最多180天）"
                            }
                        ]
                    },
                    {
                        "productCode":"FA002177",
                        "productName":"驾乘无忧C（疫安心版）",
                        "policyType":"2",
                        "amount":892500,
                        "premium":"300",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"283",
                        "effectiveShare":"1",
                        "propAccidentComboList":[
                            {
                                "comboName":"锦程交通意外伤害保险",
                                "coverage":"75万",
                                "comboDetail":"交通意外身故残疾"
                            },
                            {
                                "comboName":"交通意外伤害医疗保险",
                                "coverage":"7.5万",
                                "comboDetail":"交通意外医疗"
                            },
                            {
                                "comboName":"意外伤害住院医疗补助条款",
                                "coverage":"375元/天",
                                "comboDetail":"意外伤害住院补助（最多180天）"
                            }
                        ]
                    },
                    {
                        "productCode":"FA002178",
                        "productName":"驾乘无忧D（疫安心版）",
                        "policyType":"2",
                        "amount":1190000,
                        "premium":"400",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "effectiveShare":"1",
                        "propAccidentComboList":[
                            {
                                "comboName":"锦程交通意外伤害保险",
                                "coverage":"100万",
                                "comboDetail":"交通意外身故残疾"
                            },
                            {
                                "comboName":"交通意外伤害医疗保险",
                                "coverage":"10万",
                                "comboDetail":"交通意外医疗"
                            },
                            {
                                "comboName":"意外伤害住院医疗补助条款",
                                "coverage":"500元/天",
                                "comboDetail":"意外伤害住院补助（最多180天）"
                            }
                        ]
                    },
                    {
                        "productCode":"FA002179",
                        "productName":"驾乘无忧E（疫安心版）",
                        "policyType":"2",
                        "amount":1785000,
                        "premium":"500",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"491",
                        "effectiveShare":"1",
                        "propAccidentComboList":[
                            {
                                "comboName":"锦程交通意外伤害保险",
                                "coverage":"150万",
                                "comboDetail":"交通意外身故残疾"
                            },
                            {
                                "comboName":"交通意外伤害医疗保险",
                                "coverage":"15万",
                                "comboDetail":"交通意外医疗"
                            },
                            {
                                "comboName":"意外伤害住院医疗补助条款",
                                "coverage":"750元/天",
                                "comboDetail":"意外伤害住院补助（最多180天）"
                            }
                        ]
                    },
                    {
                        "productCode":"FA004890",
                        "productName":"渠道版车家益-全家钻石版（双节特惠）",
                        "policyType":"2",
                        "amount":4459000,
                        "premium":"1899",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"1821",
                        "effectiveShare":"1",
                        "propAccidentComboList":[
                            {
                                "coverage":"4459000",
                                "comboDetail":"渠道版车家益-全家钻石版（双节特惠）"
                            }
                        ]
                    },
                    {
                        "productCode":"FA004645",
                        "productName":"车家益-全家黄金版",
                        "policyType":"2",
                        "amount":2670000,
                        "premium":"669",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"641",
                        "effectiveShare":"10",
                        "propAccidentComboList":[
                            {
                                "coverage":"2670000",
                                "comboDetail":"车家益-全家黄金版"
                            }
                        ]
                    },
                    {
                        "productCode":"FA004685",
                        "productName":"渠道版车家益-全家白银版",
                        "policyType":"2",
                        "amount":899000,
                        "premium":"699",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"669",
                        "effectiveShare":"1",
                        "propAccidentComboList":[
                            {
                                "coverage":"899000",
                                "comboDetail":"渠道版车家益-全家白银版"
                            }
                        ]
                    },
                    {
                        "productCode":"FA004885",
                        "productName":"车家益-全家钻石版（双节特惠）",
                        "policyType":"2",
                        "amount":4450000,
                        "premium":"969",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"969",
                        "effectiveShare":"1",
                        "propAccidentComboList":[
                            {
                                "coverage":"4450000",
                                "comboDetail":"车家益-全家钻石版（双节特惠）"
                            }
                        ]
                    },
                    {
                        "productCode":"FA004884",
                        "productName":"车家益-全家黄金版（双节特惠）",
                        "policyType":"2",
                        "amount":2670000,
                        "premium":"609",
                        "isDefault":"0",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"609",
                        "effectiveShare":"1",
                        "propAccidentComboList":[
                            {
                                "coverage":"2670000",
                                "comboDetail":"车家益-全家黄金版（双节特惠）"
                            }
                        ]
                    }
                ],
                "planName":"交通意外险"
            },
            {
                "isDefault":"0",
                "planCode":"0000",
                "propAccidentProductList":[
                    {
                        "model":"100",
                        "productCode":"ZH000001",
                        "productName":"组合方案简称",
                        "policyType":"2",
                        "amount":2127000,
                        "premium":"760",
                        "isDefault":"0",
                        "carUseType":"99",
                        "actualShare":"1",
                        "premiumType":"1",
                        "netPremium":"736",
                        "effectiveShare":"1",
                        "operatingAttribute":"00",
                        "maximumSeats":"5",
                        "propAccidentComboList":[
                            {
                                "comboName":"锦程交通意外伤害保险",
                                "coverage":"1500000.00",
                                "comboDetail":"锦程交通意外伤害保险"
                            },
                            {
                                "comboName":"意外伤害住院医疗补助保险",
                                "coverage":"135000.00",
                                "comboDetail":"意外伤害住院医疗补助保险"
                            },
                            {
                                "comboName":"交通意外伤害医疗保险",
                                "coverage":"150000.00",
                                "comboDetail":"交通意外伤害医疗保险"
                            },
                            {
                                "comboName":"意外身故伤残保险责任",
                                "coverage":"300000.00",
                                "comboDetail":"意外身故伤残保险责任"
                            },
                            {
                                "comboName":"意外伤害住院津贴保险责任",
                                "coverage":"9000.00",
                                "comboDetail":"意外伤害住院津贴保险责任"
                            },
                            {
                                "comboName":"意外伤害医疗保险责任",
                                "coverage":"30000.00",
                                "comboDetail":"意外伤害医疗保险责任"
                            },
                            {
                                "comboName":"随车行李物品损失保险",
                                "coverage":"3000.00",
                                "comboDetail":"随车行李物品损失保险"
                            }
                        ]
                    }
                ],
                "planName":"组合方案简称"
            }
        ],
        "hasRcldFlag":"0",
        "totalDiscount":"0.500",
        "showDiscountFlag":"1",
        "nopeSameStartDateFlag":"1",
        "elrLevelALL":"d2",
        "jyxRiskDataList":[
            {
                "amount":"0",
                "coverageCode":"0895001",
                "coverageName":"驾乘人员意外伤害保险",
                "riskCode":"0895",
                "coverageType":"0",
                "deductableFlag":"0",
                "mainCoverageCode":"",
                "riskRuleList":[
                    "0",
                    "10000",
                    "20000",
                    "50000",
                    "100000",
                    "200000",
                    "300000",
                    "500000",
                    "800000",
                    "1000000",
                    "3000000",
                    "4000000",
                    "5000000",
                    "6000000",
                    "8000000",
                    "10000000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"0895002",
                "coverageName":"驾乘人员意外伤害医疗保险",
                "riskCode":"0895",
                "coverageType":"0",
                "deductableFlag":"0",
                "mainCoverageCode":"",
                "riskRuleList":[
                    "0",
                    "10000",
                    "20000",
                    "50000",
                    "100000",
                    "200000",
                    "300000",
                    "400000",
                    "500000",
                    "600000",
                    "800000",
                    "1000000",
                    "1500000",
                    "2000000",
                    "3000000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"0895003",
                "coverageName":"附加住院津贴保险",
                "riskCode":"0895",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"0895001,0895002",
                "riskRuleList":[
                    "0",
                    ""
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            },
            {
                "amount":"0",
                "coverageCode":"0895004",
                "coverageName":"附加超额医疗费用补偿险",
                "riskCode":"0895",
                "coverageType":"1",
                "deductableFlag":"0",
                "mainCoverageCode":"0895001,0895002",
                "riskRuleList":[
                    "0",
                    "10000",
                    "20000",
                    "50000",
                    "100000"
                ],
                "calculateFlag":"0",
                "floatAmountFlag":"0",
                "amountLabel":"不投保"
            }
        ],
        "originalTotalPremium":"5346.64",
        "originalBiPremium":"5346.64",
        "premfactor4":"1.0",
        "premfactorPrice":"0.5",
        "orderTaxInfoDTO":{

        },
        "insuredStatus":"0",
        "scxlDTO":{

        },
        "needPureRangeFlag":"0",
        "rcldDTOList":[

        ],
        "resultCode":"0"
    },
    "resultCode":"0",
    "resultMessage":"调用成功！"
}


let arr=obj.responseObject.riskDataList


arr.forEach((item,key)=>{
  console.log(item)
  if(item.amount=='-1.00'){
    item.amount='共享保额'
  }

})